/**
 * 국가 목록: ISO 코드 → 한국어 이름(첫 번째) | 별칭들(영문 포함)
 * 여기에 없는 나라는 시트의 '국가목록' 탭에 직접 추가하면 됩니다.
 */
const COUNTRY_DATA = [
  // 동아시아
  'KR:대한민국|한국|Korea|South Korea',
  'JP:일본|Japan|오사카|도쿄|후쿠오카|오키나와|삿포로|교토',
  'CN:중국|China|상하이|베이징|칭다오',
  'TW:대만|타이완|Taiwan|타이베이',
  'HK:홍콩|Hong Kong',
  'MO:마카오|Macau|Macao',
  'MN:몽골|Mongolia',
  // 동남아시아
  'TH:태국|Thailand|방콕|푸켓|치앙마이',
  'VN:베트남|Vietnam|Viet Nam|다낭|나트랑|하노이|호치민|푸꾸옥|호이안',
  'PH:필리핀|Philippines|세부|보라카이|보홀|마닐라',
  'SG:싱가포르|싱가폴|Singapore',
  'MY:말레이시아|Malaysia|코타키나발루|쿠알라룸푸르',
  'ID:인도네시아|Indonesia|발리|Bali|자카르타',
  'KH:캄보디아|Cambodia|씨엠립|앙코르와트',
  'LA:라오스|Laos|비엔티안|방비엥',
  'MM:미얀마|Myanmar',
  'BN:브루나이|Brunei',
  'TL:동티모르|Timor-Leste',
  // 남아시아·중앙아시아
  'IN:인도|India',
  'NP:네팔|Nepal',
  'LK:스리랑카|Sri Lanka',
  'MV:몰디브|Maldives',
  'BD:방글라데시|Bangladesh',
  'PK:파키스탄|Pakistan',
  'BT:부탄|Bhutan',
  'KZ:카자흐스탄|Kazakhstan',
  'UZ:우즈베키스탄|Uzbekistan',
  'KG:키르기스스탄|Kyrgyzstan',
  'TJ:타지키스탄|Tajikistan',
  'TM:투르크메니스탄|Turkmenistan',
  // 중동
  'AE:아랍에미리트|UAE|두바이|아부다비|United Arab Emirates',
  'TR:튀르키예|터키|Turkey|Türkiye|이스탄불',
  'IL:이스라엘|Israel',
  'JO:요르단|Jordan',
  'QA:카타르|Qatar|도하',
  'SA:사우디아라비아|사우디|Saudi Arabia',
  'OM:오만|Oman',
  'BH:바레인|Bahrain',
  'KW:쿠웨이트|Kuwait',
  'IR:이란|Iran',
  'IQ:이라크|Iraq',
  'LB:레바논|Lebanon',
  'SY:시리아|Syria',
  'YE:예멘|Yemen',
  'AF:아프가니스탄|Afghanistan',
  'GE:조지아|Georgia',
  'AM:아르메니아|Armenia',
  'AZ:아제르바이잔|Azerbaijan',
  'CY:키프로스|사이프러스|Cyprus',
  // 유럽
  'GB:영국|UK|United Kingdom|England|런던|스코틀랜드',
  'FR:프랑스|France|파리',
  'DE:독일|Germany',
  'IT:이탈리아|Italy|로마|베네치아|피렌체',
  'ES:스페인|Spain|바르셀로나|마드리드',
  'PT:포르투갈|Portugal|리스본',
  'NL:네덜란드|Netherlands|암스테르담',
  'BE:벨기에|Belgium',
  'LU:룩셈부르크|Luxembourg',
  'CH:스위스|Switzerland',
  'AT:오스트리아|Austria|빈|비엔나',
  'CZ:체코|Czech|Czechia|프라하',
  'HU:헝가리|Hungary|부다페스트',
  'PL:폴란드|Poland',
  'SK:슬로바키아|Slovakia',
  'SI:슬로베니아|Slovenia',
  'HR:크로아티아|Croatia',
  'BA:보스니아 헤르체고비나|보스니아|Bosnia',
  'RS:세르비아|Serbia',
  'ME:몬테네그로|Montenegro',
  'MK:북마케도니아|North Macedonia',
  'AL:알바니아|Albania',
  'XK:코소보|Kosovo',
  'GR:그리스|Greece|산토리니|아테네',
  'BG:불가리아|Bulgaria',
  'RO:루마니아|Romania',
  'MD:몰도바|Moldova',
  'UA:우크라이나|Ukraine',
  'BY:벨라루스|Belarus',
  'RU:러시아|Russia|블라디보스토크',
  'EE:에스토니아|Estonia',
  'LV:라트비아|Latvia',
  'LT:리투아니아|Lithuania',
  'FI:핀란드|Finland|헬싱키',
  'SE:스웨덴|Sweden',
  'NO:노르웨이|Norway',
  'DK:덴마크|Denmark',
  'IS:아이슬란드|Iceland',
  'IE:아일랜드|Ireland',
  'MT:몰타|Malta',
  'MC:모나코|Monaco',
  'VA:바티칸|Vatican',
  'SM:산마리노|San Marino',
  'LI:리히텐슈타인|Liechtenstein',
  'AD:안도라|Andorra',
  // 아메리카
  'US:미국|USA|United States|뉴욕|로스앤젤레스|하와이|라스베이거스|샌프란시스코',
  'CA:캐나다|Canada|밴쿠버|토론토',
  'MX:멕시코|Mexico|칸쿤',
  'GU:괌|Guam',
  'MP:사이판|북마리아나 제도|Saipan|Northern Mariana Islands',
  'PR:푸에르토리코|Puerto Rico',
  'CU:쿠바|Cuba',
  'JM:자메이카|Jamaica',
  'DO:도미니카 공화국|Dominican Republic',
  'BS:바하마|Bahamas',
  'GT:과테말라|Guatemala',
  'CR:코스타리카|Costa Rica',
  'PA:파나마|Panama',
  'BR:브라질|Brazil',
  'AR:아르헨티나|Argentina',
  'CL:칠레|Chile',
  'PE:페루|Peru|마추픽추',
  'BO:볼리비아|Bolivia|우유니',
  'CO:콜롬비아|Colombia',
  'EC:에콰도르|Ecuador',
  'UY:우루과이|Uruguay',
  'PY:파라과이|Paraguay',
  'VE:베네수엘라|Venezuela',
  // 오세아니아
  'AU:호주|오스트레일리아|Australia|시드니|멜버른',
  'NZ:뉴질랜드|New Zealand',
  'FJ:피지|Fiji',
  'PW:팔라우|Palau',
  'PF:프랑스령 폴리네시아|타히티|Tahiti',
  'NC:뉴칼레도니아|New Caledonia',
  'WS:사모아|Samoa',
  'TO:통가|Tonga',
  'VU:바누아투|Vanuatu',
  'PG:파푸아뉴기니|Papua New Guinea',
  'FM:미크로네시아|Micronesia',
  'MH:마셜 제도|Marshall Islands',
  // 아프리카
  'EG:이집트|Egypt',
  'MA:모로코|Morocco',
  'TN:튀니지|Tunisia',
  'ZA:남아프리카공화국|남아공|South Africa',
  'KE:케냐|Kenya',
  'TZ:탄자니아|Tanzania|잔지바르',
  'ET:에티오피아|Ethiopia',
  'MU:모리셔스|Mauritius',
  'SC:세이셸|Seychelles',
  'MG:마다가스카르|Madagascar',
  'NA:나미비아|Namibia',
  'BW:보츠와나|Botswana',
  'ZW:짐바브웨|Zimbabwe',
  'ZM:잠비아|Zambia',
  'NG:나이지리아|Nigeria',
  'GH:가나|Ghana',
  'SN:세네갈|Senegal',
  'RW:르완다|Rwanda',
  'UG:우간다|Uganda',
];
